In [4]:
import pandas as pd

df = pd.read_csv('C:/Users/Sut Zaw Aung/StockMarketDB/pythonProjectBank/data/row/c_accounts.csv')

rows = []

balance_series = df['balance']

rows.append({'Column': 'Balance', 'Dtype': 'float64', 'Value': 'Total Accounts', 'Count': balance_series.count()})
rows.append({'Column': 'Balance', 'Dtype': 'float64', 'Value': 'Total Sum', 'Count': balance_series.sum()})
rows.append({'Column': 'Balance', 'Dtype': 'float64', 'Value': 'Mean', 'Count': balance_series.mean()})
rows.append({'Column': 'Balance', 'Dtype': 'float64', 'Value': 'Median', 'Count': balance_series.median()})
rows.append({'Column': 'Balance', 'Dtype': 'float64', 'Value': 'Min', 'Count': balance_series.min()})
rows.append({'Column': 'Balance', 'Dtype': 'float64', 'Value': 'Max', 'Count': balance_series.max()})
rows.append({'Column': 'Balance', 'Dtype': 'float64', 'Value': 'Std Deviation', 'Count': balance_series.std()})

# Define bins for balance distribution
bins = [0, 5000000, 10000000, 20000000, 50000000, 100000000]
labels = ['<5M', '5M-10M', '10M-20M', '20M-50M', '>50M']

# Calculate balance distribution
balance_distribution = pd.cut(balance_series, bins=bins, labels=labels, right=False).value_counts().sort_index()

# Append balance distribution to the rows
for label, count in balance_distribution.items():
    rows.append({
        'Column': 'Balance Range',
        'Dtype': 'category',
        'Value': label,
        'Count': count
    })

result_df = pd.DataFrame(rows)

display(result_df)

           Column     Dtype           Value         Count
0         Balance   float64  Total Accounts  1.516000e+03
1         Balance   float64       Total Sum  3.766932e+10
2         Balance   float64            Mean  2.484784e+07
3         Balance   float64          Median  2.471635e+07
4         Balance   float64             Min  1.178523e+04
5         Balance   float64             Max  4.999771e+07
6         Balance   float64   Std Deviation  1.448991e+07
7   Balance Range  category             <5M  1.620000e+02
8   Balance Range  category          5M-10M  1.570000e+02
9   Balance Range  category         10M-20M  2.880000e+02
10  Balance Range  category         20M-50M  9.090000e+02
11  Balance Range  category            >50M  0.000000e+00